apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-deploy-cka
  namespace: dns-ns
  labels:
    app: dsnapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnsapp
  template:
    metadata:
      labels:
        app: dnsapp
    spec:
      containers:
      - name: dns-container
        image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
        command: ["sleep"]
        args: ["3600"]
        ports:
        - containerPort: 80